; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#include "CodeDependencies.iss"

#define MyAppName "QSM.Windows"
#define MyAppVersion "1.3.2"
#define MyAppPublisher "Satakun Utama"
#define MyAppURL "https://linesofcodes.dailitation.xyz/QSMSharp/"
#define MyAppExeName "QSM.Windows.exe"
#define ProjectRoot "C:\Users\Satakun Utama\QSMSharp"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{92BAD0EC-6375-411C-995E-216BEF2E27B2}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; Uses the new 64-bit installer in Inno Setup 7
; Will make the installer use the 64-bit Program Files directory and registry view,
; while also specifying that the setup cannot run on anything but 64-bit systems
SetupArchitecture=x64
DisableProgramGroupPage=yes
LicenseFile="{#ProjectRoot}\QSM.Windows\gpl-3.0.rtf"
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=QSMWindows-x64-{#MyAppVersion}
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
#expr EmitLanguagesSection

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#ProjectRoot}\QSM.Windows\bin\x64\Release\net10.0-windows10.0.26100.0\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ProjectRoot}\QSM.Windows\bin\x64\Release\net10.0-windows10.0.26100.0\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
function InitializeSetup: Boolean;
begin
  Dependency_AddDotNet100Desktop;
  Result := True;
end;
